### PR TITLE
Hyperbola DLCs

### PR DESCRIPTION
**Pull request by nkohen**
Built on top of #2824 

Implements https://github.com/discreetlogcontracts/dlcspecs/pull/144

### CODE REVIEW

**Comment by benthecarman** [comment]
compile failing

**Comment by Christewart** [comment]
needs rebase

**Comment by Christewart** [comment]
I believe we need to merge this PR to pass tibo's test vectors (`single_oracle_numerical_test.json`)

https://github.com/discreetlogcontracts/dlcspecs/pull/163/files#diff-c9f013f3dc4af993414bc283aee2a85ccc848747aeef3db3f3bb96e60324c3b0R21

**Comment by Christewart** [comment]
Done in #3854

**Pull request closed without merging**
