### PR TITLE
Handle failed getting version of bitcoind

### PR DESCRIPTION
**Pull request by benthecarman**
@tompro reported that he was getting failures when trying to get the bitcoind version. We should just default to the newest version in this case.

### CODE REVIEW

**Comment by benthecarman** [comment]
getting this when trying to run
image

seems this is not our fault, however, I still think this would be a useful change

**Comment by Christewart** [comment]
> getting this when trying to run image
> 
> seems this is not our fault, however, I still think this would be a useful change

@tompro Can you try closing your terminal and re-opening it? Sometimes on mac downloaded binaries are not valid in the current terminal session. If you create a new terminal, it sometimes just works :tm: . I'm not sure why.

**Comment by tompro** [comment]
@Christewart I already did open new terminals, also added the permission exception in MacOS.

**Comment by Christewart** [comment]
> @Christewart I already did open new terminals, also added the permission exception in MacOS.

What did you have to run ? Was it something similar to this? 

https://github.com/bitcoin-s/bitcoin-s/blob/2001e86ab94019dd468aaa658695620626e19e98/app/server/src/universal/wallet-server-extra-startup-script.sh#L18

**Comment by tompro** [comment]
You can add the exception in Privacy & Security settings UI right after you launch the bin. The message above is not from a launch via SBT but directly launching the bitcoind bin (freshly downloaded from https://bitcoincore.org/bin/bitcoin-core-23.0/bitcoin-23.0-arm64-apple-darwin.tar.gz) . I was just verifying if bitcoind is executable at all. It behaves the same as the bin downloaded via SBT.

**Review by Christewart — COMMENTED** [review]
So did @tompro build bitcoin from source resulting ina version of that was something like `23.99`? I'm confused otherwise how he got an invalid version from bitcoincore.org

**Comment by tompro** [comment]
Nope I just ran the bin as downloaded. Reason might be m2 or recent MacOs update:
image

**Comment by Christewart** [comment]
> Nope I just ran the bin as downloaded. Reason might be m2 or recent MacOs update: image

oooh! Nice, i hear the m2 chip has a ~30% performance improvement over the m1 chip (!!!). 

I only have an m1, so you may experience other weird things. Please report bugs if you find them :-)

**Review by Christewart — APPROVED** [review]

**Pull request merged**
