### PR TITLE
init 1.9.8 release notes

### PR DESCRIPTION
**Pull request by Christewart**

### CODE REVIEW

**Comment by kamilkloch** [comment]
Any ETA on 1.9.8? :)

**Comment by Christewart** [comment]
> Any ETA on 1.9.8? :)

I'm hoping next week! Anything you need in particular?

**Comment by kamilkloch** [comment]
> I'm hoping next week! Anything you need in particular?

Thank you for asking! Support for generating multisig addresses in bech32 and  bech32m formats would be nice.

**Comment by Christewart** [comment]
> > I'm hoping next week! Anything you need in particular?
> 
> Thank you for asking! Support for generating multisig addresses in bech32 and bech32m formats would be nice.

I'm planning on reworking the wallet to be taproot native in 1.9.9. You should be able to make `bech32` addresses with multisig right now, but `bech32m` will have to be reworked to support the new multisig opcode called `OP_CHECKSIGADD`. 


For generating a multisig bech32 address: 

1. Generate a [`MultiSignatureScriptPubKey`](https://github.com/bitcoin-s/bitcoin-s/blob/be1ec842c2fef622985f713357536b73352eb3aa/core/src/main/scala/org/bitcoins/core/protocol/script/ScriptPubKey.scala#L199) from a set of public keys and a required amount of signatures
2. Create a [`WitnessScriptPubKeyV0`](https://github.com/bitcoin-s/bitcoin-s/blob/be1ec842c2fef622985f713357536b73352eb3aa/core/src/main/scala/org/bitcoins/core/protocol/script/ScriptPubKey.scala#L1408) from the `MultiSignatureScriptPubKey` in step `1`.
3. Create a [`Bech32Address`](https://github.com/bitcoin-s/bitcoin-s/blob/676c0b42617576598b9412e3f5149822b62d81ed/core/src/main/scala/org/bitcoins/core/protocol/Address.scala#L139) from the `WitnessScriptPubKeyV0` in step `2`.

 If you want the multisig address to be added to the wallet and track signing state, that isn't possible IIRC.

**Pull request merged**
