### PR TITLE
Config CLI option, datadir correctly read from config

### LINKED ISSUE #1787: bitcoin-s.datadir config setting not working
When trying to use bitcoin-s as a backend for eclair, we have the setting for the bitcoin-s datadir here: 

https://github.com/rorp/eclair/blob/bitcoin-s-integration/eclair-core/src/main/resources/reference.conf#L229

As discussed on slack, we should probably have both `--conf` and `--datadir` options. Obviously you can't have a `bitcoin-s.conf` option the config file though as that is self referential. You should be able to configure a datadir from the `bitcoin-s.conf` file though. 

I started eclair with this setting:

> ./eclair-node.sh -Declair.datadir=/tmp/eclair-bitcoin-s

You can see that the initialization happens for the wallet/key-manager rather than using the setting I have in `bitcoin-s.datadir`

>2020-08-07T20:39:33 INFO [WALLET] Initializing key manager
2020-08-07T20:39:33 INFO [WALLET] Creating new wallet
2020-08-07T20:39:34 INFO [WALLET] Created account=AccountDb(tpubDCdA7r6mN442hVgkgszungRU3VyNwk68Jk5wevNxYacvXxwrnBqy8FWLEmZmrQQCoHaa5mu62ZzbS3ZLTS2Unn1AiuFAedYZTATZznwGmfi,m/44'/1'/0') to DB
2020-08-07T20:39:34 INFO [WALLET] Created account=AccountDb(vpub5Yov9o5iBf6WdLRsLJLWS9ar5B1xKAj5y7V8xZ9ZXhrVswcq4FWAcVtkurqdQALxpFQwoVRgJ8T8rbGRYssGVVx7oBsvrhGm6

and you can see the files being created in the `-Declair.datadir` 

> ls
eclair.log  encrypted-bitcoin-s-seed.json  keys.log  mainnet  seed.dat  testnet3
➜  eclair-bitcoin-s pwd
/tmp/eclair-bitcoin-s

rather than my expected datadir of `$HOME/.bitcoin-s/`

### LINKED ISSUE #1795: Add cli option for setting config file
We should be able to specify a `bitcoin-s.conf` file as a command line option instead of always just reading the config option at `~/.bitcoin-s/bitcoin-s.conf`. This when then enable us to use the `datadir` config option.

### PR DESCRIPTION
**Pull request by benthecarman**
Fixes #1795 
Fixes #1787 

Needed to do both of these in one as they both were highly reliant on eachother.

### CODE REVIEW

**Comment by Christewart** [comment]
Seems like we have a bunch of logs showing up now on tests? https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/717333892#L634

**Comment by Christewart** [comment]
So I tried to run this with

```
 ./bitcoin-s-server --datadir /tmp/tmp-bitcoin-s
```
which I expect to use my conf in `$HOME/.bitcoin-s/bitcoin-s.conf`. I would _expect_ this to start syncing a fresh testnet3 node with a new wallet etc. For some reason I am attempting to connect to a regtest node. 

> 2020-08-12T18:51:32 DEBUG [ChainAppConfig] DB path: /tmp/tmp-bitcoin-s/regtest
2020-08-12T18:51:41 ERROR [P2P] Failed to connect with peer=Peer(/127.0.0.1:18444) with err=org.bitcoins.rpc.util.AsyncUtil$RpcRetryException: Condition timed out after 50 attempts with 100 milliseconds waiting periods
2020-08-12T18:51:41 ERROR [P2P] Cannot start Neutrino node
org.bitcoins.rpc.util.AsyncUtil$RpcRetryException: Condition timed out after 50 attempts with 100 milliseconds waiting periods
        at org.bitcoins.node.Node.$anonfun$start$5(Node.scala:124)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
^C% 

The first few lines in `$HOME/.bitcoin-s/bitcoin-s.conf` are 

>bitcoin-s {
    datadir = ${HOME}/.bitcoin-s
    network = testnet3# regtest, testnet3, mainnet
   ...

**Comment by benthecarman** [comment]
> which I expect to use my conf in $HOME/.bitcoin-s/bitcoin-s.conf. I would expect this to start syncing a fresh testnet3 node with a new wallet etc.

I have it set to read the conf that's in the datadir. I would say should be the expected behavior because if you are changing the entire datadir then you shouldn't need to change the config along with it.

**Comment by Christewart** [comment]
Ok all of these work for me!

>./bitcoin-s-server --conf /tmp/tmp-bitcoin-s/bitcoin-s.conf

and 

>./bitcoin-s-server --datadir /tmp/tmp-bitcoin-s --conf $HOME/.bitcoin-s/bitcoin-s.conf

and setting `bitcoin-s.datadir` in the config file directly!

**Review by Christewart — APPROVED** [review]
LGTM assuming we get documentation for `--conf`

**Review by Christewart — APPROVED** [review]

**Pull request merged**
