### PR TITLE
Sort DLC table by last updated

### LINKED ISSUE #3606: Make latest DLC appear at the top of the table view
It seems like they randomly get inserted into the table view at the moment, we should make the latest DLC be at the top of the table

### PR DESCRIPTION
**Pull request by benthecarman**
Fixes #3606

Adds a `lastUpdated` column to the dlcdb and sorts the table by this

### CODE REVIEW

**Review by Christewart — CHANGES_REQUESTED** [review]
This looks reasonable to me, can we add this in `core` or `db-commons` somewhere?

```scala
trait LastUpdatedDb {
  /** The time this object as last updated in the database */
  def lastUpdated: Instant
}
```

and extend it where needed so we have some sort of a common interface

**Review by Christewart — CHANGES_REQUESTED** [review]
I don't see the column? This is on  946b9537927079e0afbc4d171d925d38fd31f958


Screenshot from 2021-08-26 08-41-18

**Comment by Christewart** [comment]
Compile fails: https://github.com/bitcoin-s/bitcoin-s/pull/3607/checks?check_run_id=3436160533#step:5:356

**Comment by Christewart** [comment]
What i see now

Screenshot from 2021-08-27 09-02-39

Perhaps we want the default to be more recent? Also maybe adding hours and minutes would be worthwhile to the GUI?

**Comment by benthecarman** [comment]
> Perhaps we want the default to be more recent? 

I tried doing `CURRENT_TIMESTAMP` but flyway wouldn't let me, saying it needs to be static, so I just set it to 0. Maybe we can set it to today or something

**Comment by Christewart** [comment]
What i get on startup on  b8f1f7d465be2d7e337acb302102bc5e6cba88f1 

Screenshot from 2021-08-31 13-34-17

```
[error] java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: MonthOfYear
[error]         at java.base/java.time.Instant.getLong(Instant.java:603)
[error]         at java.base/java.time.format.DateTimePrintContext$1.getLong(DateTimePrintContext.java:205)
[error]         at java.base/java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:308)
[error]         at java.base/java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2704)
[error]         at java.base/java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2343)
[error]         at java.base/java.time.format.DateTimeFormatterBuilder$LocalizedPrinterParser.format(DateTimeFormatterBuilder.java:4785)
[error]         at java.base/java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2343)
[error]         at java.base/java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1848)
[error]         at java.base/java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1822)
[error]         at org.bitcoins.gui.dlc.DLCTableView$$anon$7.$anonfun$new$8(DLCTableView.scala:92)
[error]         at scalafx.scene.control.TableColumn$$anon$2.call(TableColumn.scala:252)
[error]         at scalafx.scene.control.TableColumn$$anon$2.call(TableColumn.scala:250)
[error]         at javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:593)
[error]         at javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:578)
[error]         at javafx.scene.control.TableCell.updateItem(TableCell.java:646)
[error]         at javafx.scene.control.TableCell.indexChanged(TableCell.java:469)
[error]         at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
[error]         at javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:539)
[error]         at javafx.scene.control.skin.TableRowSkinBase.<init>(TableRowSkinBase.java:159)
[error]         at javafx.scene.control.skin.TableRowSkin.<init>(TableRowSkin.java:89)
[error]         at javafx.scene.control.TableRow.createDefaultSkin(TableRow.java:213)
[error]         at javafx.scene.control.Control.doProcessCSS(Control.java:897)
[error]         at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
[error]         at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
[error]         at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[error]         at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
[error]         at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
[error]         at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
[error]         at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[error]         at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
[error]         at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
[error]         at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
[error]         at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[error]         at javafx.scene.Node.processCSS(Node.java:9456)
[error]         at javafx.scene.Node.applyCss(Node.java:9543)
[error]         at javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1814)
[error]         at javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1791)
[error]         at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:2966)
[error]         at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:2949)
[error]         at javafx.scene.control.skin.VirtualFlow.recalculateAndImproveEstimatedSize(VirtualFlow.java:3021)
[error]         at javafx.scene.control.skin.VirtualFlow.recalculateEstimatedSize(VirtualFlow.java:3013)
[error]         at javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1052)
[error]         at javafx.scene.control.skin.VirtualFlow$5.invalidated(VirtualFlow.java:885)
[error]         at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
[error]         at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
[error]         at javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:899)
[error]         at javafx.scene.control.skin.TableViewSkinBase.updateItemCount(TableViewSkinBase.java:554)
[error]         at javafx.scene.control.skin.TableViewSkin.<init>(TableViewSkin.java:136)
[error]         at javafx.scene.control.TableView.createDefaultSkin(TableView.java:1534)
[error]         at javafx.scene.control.Control.doProcessCSS(Control.java:897)
[error]         at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
[error]         at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
[error]         at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[error]         at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
[error]         at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
[error]         at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
[error]         at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[error]         at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
[error]         at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
[error]         at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
[error]         at com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
[error]         at com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
[error]         at javafx.scene.control.Control.doProcessCSS(Control.java:900)
[error]         at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
[error]         at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
[error]         at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[error]         at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
[error]         at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
[error]         at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
[error]         at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[error]         at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
[error]         at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
[error]         at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
[error]         at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[error]         at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
[error]         at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
[error]         at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
[error]         at com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
[error]         at com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
[error]         at javafx.scene.control.Control.doProcessCSS(Control.java:900)
[error]         at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
[error]         at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
[error]         at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[error]         at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
[error]         at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
[error]         at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
[error]         at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[error]         at javafx.scene.Node.processCSS(Node.java:9456)
[error]         at javafx.scene.Node.processCSS(Node.java:9449)
[error]         at javafx.scene.Scene.doCSSPass(Scene.java:569)
[error]         at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2474)
[error]         at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:414)
[error]         at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
[error]         at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:413)
[error]         at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:440)
[error]         at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:564)
[error]         at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:544)
[error]         at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:537)
[error]         at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:343)
[error]         at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
[error]         at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
[error]         at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
[error]         at java.base/java.lang.Thread.run(Thread.java:832)
[info] 2021-08-31T18:33:47UTC INFO [NeutrinoNode] Starting sync node, height=2090656 hash=00000000000000fa53a4ae1b31bc3d7a6b651130052d14743589662a2cd31f5f
[info] 2021-08-31T18:33:47UTC INFO [BitcoinSServerMain] Done starting Main! It took 7075ms
[error] java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: MonthOfYear
[error]         at java.base/java.time.Instant.getLong(Instant.java:603)
[error]         at java.base/java.time.format.DateTimePrintContext$1.getLong(DateTimePrintContext.java:205)
[error]         at java.base/java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:308)
[error]         at java.base/java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2704)
[error]         at java.base/java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2343)
[error]         at java.base/java.time.format.DateTimeFormatterBuilder$LocalizedPrinterParser.format(DateTimeFormatterBuilder.java:4785)
[error]         at java.base/java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2343)
[error]         at java.base/java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1848)
[error]         at java.base/java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1822)
[error]         at org.bitcoins.gui.dlc.DLCTableView$$anon$7.$anonfun$new$8(DLCTableView.scala:92)
[error]         at scalafx.scene.control.TableColumn$$anon$2.call(TableColumn.scala:252)
[error]         at scalafx.scene.control.TableColumn$$anon$2.call(TableColumn.scala:250)
[error]         at javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:593)
[error]         at javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:578)
[error]         at javafx.scene.control.TableCell.updateItem(TableCell.java:646)
[error]         at javafx.scene.control.TableCell.indexChanged(TableCell.java:469)
[error]         at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
[error]         at javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:539)
[error]         at javafx.scene.control.skin.TableRowSkinBase.<init>(TableRowSkinBase.java:159)
[error]         at javafx.scene.control.skin.TableRowSkin.<init>(TableRowSkin.java:89)
[error]         at javafx.scene.control.TableRow.createDefaultSkin(TableRow.java:213)
[error]         at javafx.scene.control.Control.doProcessCSS(Control.java:897)
[error]         at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
[error]         at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
[error]         at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[error]         at javafx.scene.Node.processCSS(Node.java:9456)
[error]         at javafx.scene.Node.applyCss(Node.java:9543)
[error]         at javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1814)
[error]         at javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1791)
[error]         at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:2966)
[error]         at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:2949)
[error]         at javafx.scene.control.skin.VirtualFlow.recalculateAndImproveEstimatedSize(VirtualFlow.java:3021)
[error]         at javafx.scene.control.skin.VirtualFlow.recalculateEstimatedSize(VirtualFlow.java:3013)
[error]         at javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1052)
[error]         at javafx.scene.Parent.layout(Parent.java:1207)
[error]         at javafx.scene.Parent.layout(Parent.java:1214)
[error]         at javafx.scene.Parent.layout(Parent.java:1214)
[error]         at javafx.scene.Parent.layout(Parent.java:1214)
[error]         at javafx.scene.Parent.layout(Parent.java:1214)
[error]         at javafx.scene.Parent.layout(Parent.java:1214)
[error]         at javafx.scene.Parent.layout(Parent.java:1214)
[error]         at javafx.scene.Parent.layout(Parent.java:1214)
[error]         at javafx.scene.Parent.layout(Parent.java:1214)
[error]         at javafx.scene.Scene.doLayoutPass(Scene.java:576)
[error]         at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2479)
[error]         at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:414)
[error]         at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
[error]         at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:413)
[error]         at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:440)
[error]         at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:564)
[error]         at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:544)
[error]         at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:537)
[error]         at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:343)
[error]         at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
[error]         at com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
[error]         at com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(GtkApplication.java:347)
[error]         at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:513)
[error]         at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
[error]         at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:636)
[error]         at javafx.stage.Stage.showAndWait(Stage.java:465)
[error]         at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
[error]         at javafx.scene.control.Dialog.showAndWait(Dialog.java:346)
[error]         at scalafx.scene.control.Dialog.showAndWait(Dialog.scala:107)
[error]         at scalafx.scene.control.Alert.showAndWait(Alert.scala:200)
[error]         at org.bitcoins.bundle.gui.BundleGUI$.$anonfun$start$1(BundleGUI.scala:82)
[error]         at com.sun.glass.ui.Application.reportException(Application.java:455)
[error]         at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
[error]         at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
[error]         at java.base/java.lang.Thread.run(Thread.java:832)
```

**Review by Christewart — APPROVED** [review]

**Pull request merged**
