### PR TITLE
Fix rolling log file

### PR DESCRIPTION
**Pull request by benthecarman**
Previously the rolling log file was not working for me, this seems to be the fix

### CODE REVIEW

**Comment by Christewart** [comment]
#4051

**Review by Christewart — CHANGES_REQUESTED** [review]
[I don't think this works](https://logback.qos.ch/manual/appenders.html#RollingFileAppender)

>To be of any use, a RollingFileAppender must have both a RollingPolicy and a TriggeringPolicy set up. However, if its RollingPolicy also implements the TriggeringPolicy interface, then only the former needs to be specified explicitly. 

For instance, the log file rolls after a certain amount time passes, or a certain amount of data stored in the log file. If you look into this further, it would also be nice to compress the log file we just produced to minimize disk space used by the archived log files ( #4051 )

**Comment by benthecarman** [comment]
Looks like it implements the triggering policy https://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy

not sure how to do the compression

**Comment by Christewart** [comment]
> Looks like it implements the triggering policy https://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy
> 
> not sure how to do the compression

Ah, sorry I didn't realize we already had `<rollingPolicy></rollingPolicy>` defined

**Review by Christewart — APPROVED** [review]

**Pull request merged**
