### PR TITLE
Fix root docker-compose.yml

### PR DESCRIPTION
**Pull request by user411**
Seems to fix issues with `docker-compose up`

### CODE REVIEW

**Comment by Christewart** [comment]
Hmm, now I seem to to get exceptions when attempting to create things on the filesystem

```
walletserver_1  | 2022-08-09T17:39:07UTC INFO [BIP39KeyManager$] Initializing wallet with seedPath=/home/bitcoin-s/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json
walletserver_1  | 2022-08-09T17:39:07UTC INFO [BIP39KeyManager$] Seed path parent directory does not exist, creating /home/bitcoin-s/.bitcoin-s/seeds
walletserver_1  | Exception in thread "main" java.nio.file.AccessDeniedException: /home/bitcoin-s/.bitcoin-s/seeds
walletserver_1  |       at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
walletserver_1  |       at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
walletserver_1  |       at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
walletserver_1  |       at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
walletserver_1  |       at java.base/java.nio.file.Files.createDirectory(Files.java:690)
walletserver_1  |       at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
walletserver_1  |       at java.base/java.nio.file.Files.createDirectories(Files.java:783)
walletserver_1  |       at org.bitcoins.keymanager.bip39.BIP39KeyManager$.initializeWithEntropy(BIP39KeyManager.scala:107)
walletserver_1  |       at org.bitcoins.keymanager.config.KeyManagerAppConfig.initializeKeyManager(KeyManagerAppConfig.scala:218)
walletserver_1  |       at org.bitcoins.keymanager.config.KeyManagerAppConfig.start(KeyManagerAppConfig.scala:112)
walletserver_1  |       at org.bitcoins.server.BitcoinSAppConfig.$anonfun$start$4(BitcoinSAppConfig.scala:88)
walletserver_1  |       at scala.collection.immutable.Vector1.map(Vector.scala:1872)
walletserver_1  |       at scala.collection.immutable.Vector1.map(Vector.scala:375)
walletserver_1  |       at org.bitcoins.server.BitcoinSAppConfig.start(BitcoinSAppConfig.scala:88)
walletserver_1  |       at org.bitcoins.server.BitcoinSServerMain.start(BitcoinSServerMain.scala:66)
walletserver_1  |       at org.bitcoins.server.BitcoinSServerMain.start(BitcoinSServerMain.scala:51)
walletserver_1  |       at org.bitcoins.server.routes.BitcoinSRunner.run(BitcoinSRunner.scala:29)
walletserver_1  |       at org.bitcoins.server.routes.BitcoinSRunner.run$(BitcoinSRunner.scala:17)
walletserver_1  |       at org.bitcoins.server.BitcoinSServerMain.run(BitcoinSServerMain.scala:51)
walletserver_1  |       at org.bitcoins.server.BitcoinSServerMain$.delayedEndpoint$org$bitcoins$server$BitcoinSServerMain$1(BitcoinSServerMain.scala:655)
walletserver_1  |       at org.bitcoins.server.BitcoinSServerMain$delayedInit$body.apply(BitcoinSServerMain.scala:633)
walletserver_1  |       at scala.Function0.apply$mcV$sp(Function0.scala:39)
walletserver_1  |       at scala.Function0.apply$mcV$sp$(Function0.scala:39)
walletserver_1  |       at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
walletserver_1  |       at scala.App.$anonfun$main$1(App.scala:76)
walletserver_1  |       at scala.App.$anonfun$main$1$adapted(App.scala:76)
walletserver_1  |       at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
walletserver_1  |       at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
walletserver_1  |       at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
walletserver_1  |       at scala.App.main(App.scala:76)
walletserver_1  |       at scala.App.main$(App.scala:74)
walletserver_1  |       at org.bitcoins.server.BitcoinSServerMain$.main(BitcoinSServerMain.scala:633)
walletserver_1  |       at org.bitcoins.server.BitcoinSServerMain.main(BitcoinSServerMain.scala)
```

**Comment by user411** [comment]
I don't know if you get the earlier one too

```
19:04:28,780 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(/home/bitcoin-s/.bitcoin-s/mainnet/bitcoin-s.log,true) call failed. java.io.FileNotFoundException: /home/bitcoin-s/.bitcoin-s/mainnet/bitcoin-s.log (No such file or directory)
	at java.io.FileNotFoundException: /home/bitcoin-s/.bitcoin-s/mainnet/bitcoin-s.log (No such file or directory)
	at 	at java.base/java.io.FileOutputStream.open0(Native Method)
	at 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:64)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:134)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at 	at akka.event.slf4j.Logger$.apply(Slf4jLogger.scala:32)
	at 	at akka.event.slf4j.SLF4JLogging.log(Slf4jLogger.scala:20)
	at 	at akka.event.slf4j.SLF4JLogging.log$(Slf4jLogger.scala:20)
	at 	at akka.event.slf4j.Slf4jLogger.log$lzycompute(Slf4jLogger.scala:56)
	at 	at akka.event.slf4j.Slf4jLogger.log(Slf4jLogger.scala:56)
	at 	at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:107)
	at 	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at 	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at 	at akka.event.slf4j.Slf4jLogger.aroundReceive(Slf4jLogger.scala:56)
	at 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at 	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at 	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at 	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJ
```

**Comment by Christewart** [comment]
> I don't know if you get the earlier one too
> 
> ```
> 19:04:28,780 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(/home/bitcoin-s/.bitcoin-s/mainnet/bitcoin-s.log,true) call failed. java.io.FileNotFoundException: /home/bitcoin-s/.bitcoin-s/mainnet/bitcoin-s.log (No such file or directory)
> 	at java.io.FileNotFoundException: /home/bitcoin-s/.bitcoin-s/mainnet/bitcoin-s.log (No such file or directory)
> 	at 	at java.base/java.io.FileOutputStream.open0(Native Method)
> 	at 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
> 	at 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
> 	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
> 	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
> 	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
> 	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)
> 	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
> 	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
> 	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
> 	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
> 	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
> 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
> 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
> 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
> 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
> 	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:64)
> 	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:134)
> 	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
> 	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
> 	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
> 	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
> 	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
> 	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
> 	at 	at akka.event.slf4j.Logger$.apply(Slf4jLogger.scala:32)
> 	at 	at akka.event.slf4j.SLF4JLogging.log(Slf4jLogger.scala:20)
> 	at 	at akka.event.slf4j.SLF4JLogging.log$(Slf4jLogger.scala:20)
> 	at 	at akka.event.slf4j.Slf4jLogger.log$lzycompute(Slf4jLogger.scala:56)
> 	at 	at akka.event.slf4j.Slf4jLogger.log(Slf4jLogger.scala:56)
> 	at 	at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:107)
> 	at 	at akka.actor.Actor.aroundReceive(Actor.scala:537)
> 	at 	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
> 	at 	at akka.event.slf4j.Slf4jLogger.aroundReceive(Slf4jLogger.scala:56)
> 	at 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
> 	at 	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
> 	at 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
> 	at 	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
> 	at 	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
> 	at 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJ
> ```

I do. I wonder if this is a permissions issue from previous runs (my `docker-compose up` would work with `0:1000`).

**Comment by user411** [comment]
It "works" with "0:1000" for me, but it puts files in the docker image at /root/* instead of /home/bitcoin-s/.bitcoin-s/ and does not mount them on the external file system. Are you saying it works to mount them on the external file system for you with "0:1000"?

**Comment by Christewart** [comment]
> It "works" with "0:1000" for me, but it puts files in the docker image at /root/* instead of /home/bitcoin-s/.bitcoin-s/ and does not mount them on the external file system. 

I'm not sure what is going on with environment frankly. 

When running on 89dffdff6ad368eee58e50187963fb88c188f4a8

I don't see to have anything in `/root` or `/home/bitcoin-s/`.

Screenshot from 2022-08-09 13-13-29


When running `docker-compose up` multiple times in succession on 89dffdff6ad368eee58e50187963fb88c188f4a8 it does seem like state is being saved somewhere, because my neutrino node doesn't start from block 0 every time when syncing. I'm not sure where it's being written to the filesystem though.

EDIT: 
When looking at the logs closer, it does have the `/root` path 

>seedPath=/root/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json, rootXpub=zpub6jftahH18ngZwDe5ABvo3jYusLMitXFdwjfX5PFyLuJz2qdUxssZjCtBBUejfBjzCFJFsNVv4Veay5o9Zptp7iXozXmgfaW9cgrScDvSJ

**Comment by Christewart** [comment]
I tried running this on an environment that i didn't previous run `docker-compose up` on every, and this worked like a charm. All volume data written to `/data/wallet/`. 

I'm not sure how to fix my desktop state, but this works well on mac :tada: .

**Comment by user411** [comment]
This makes me think there is some fundamental difference either between the ARM env and the x64 env or between the Mac env and the Linux env considering I am seeing the same behavior in a linux x64 vm that you were seeing on your desktop linux x64 env.

**Comment by Christewart** [comment]
superseded by #4599

**Pull request closed without merging**
