### PR TITLE
Lnd 0.16.0 rpc

### PR DESCRIPTION
**Pull request by benthecarman**
using lnd 0.16.0 rc1, wanted to run the release through our tests, looks like everything is good

### CODE REVIEW

**Comment by Christewart** [comment]
rebased this, there are some CI fixes that have gone into master

**Comment by benthecarman** [comment]
Lnd released!

**Comment by Christewart** [comment]
Some sort of error? https://github.com/bitcoin-s/bitcoin-s/actions/runs/4555754664/jobs/8035208125?pr=5005#step:5:863

**Comment by benthecarman** [comment]
> Some sort of error?

Looks like an intermittent issue, adding this sleep made it not show up for me (however it rarely showed up locally)

**Comment by benthecarman** [comment]
Should be good now

**Pull request merged**
