### PR TITLE
Bump SBT version to 0.13.17

### PR DESCRIPTION
**Pull request by mecampbellsoup**
Addresses: https://github.com/bitcoin-s/bitcoin-s-core/issues/127

### CODE REVIEW

**Comment by mecampbellsoup** [comment]
@Christewart this only bumps the SBT version; the other changes are just formatting that for some reason didn't get checked in to the previous formatting PR.

**Comment by Christewart** [comment]
Seems like the sbt `0.13.7` stuff is pulling really slowly into travis. The build is timing out. I'll try to restart later tonight / tomorrow to see if it speeds up at all

**Comment by mecampbellsoup** [comment]
@Christewart I tweaked `.travis.yml` a bit to use caching per [the sbt docs](https://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html#Caching):  https://github.com/bitcoin-s/bitcoin-s-core/pull/132/commits/a77bcd0f858890c14310a4e266b9c9df4da040f7

I think the last run just had slow fuzzy test runs and took longer than usual; a retry may've gotten the build green again as well.

**Comment by Christewart** [comment]
Great work @mecampbellsoup. Perhaps you want to take a look at #121 since you are on a travis role? It's trying to get travis to build on osx as well. Feel free to rip the code and start a new PR

**Pull request merged**
