### PR TITLE
Submodule secp256k1 instead of copying files

### PR DESCRIPTION
**Pull request by mecampbellsoup**
Inpsired by: https://github.com/ACINQ/bitcoin-lib/pull/17/files

### CODE REVIEW

**Comment by mecampbellsoup** [comment]
@Christewart how to trigger the build checks e.g. Coveralls?

**Comment by mecampbellsoup** [comment]
```
[info] ! EscrowWithTimeoutScriptSigSpec.serialization symmetry: Exception raised on property evaluation.
[info] > Exception: java.lang.UnsatisfiedLinkError: org.bitcoin.NativeSecp256k1.secp256k1_ec_pubkey_decompress(Ljava/nio/ByteBuffer;JI)[[B

[info] ! P2PKScriptPubKeySpec.Serialization symmetry: Exception raised on property evaluation.
[info] > Exception: java.lang.UnsatisfiedLinkError: org.bitcoin.NativeSecp256k1.secp256k1_ec_pubkey_decompress(Ljava/nio/ByteBuffer;JI)[[B

[info] ! ECDigitalSignatureSpec.must create and verify a digital signature: Exception raised on property evaluation.
[info] > ARG_0: DoubleSha256DigestImpl(10e5a184d30854be4d8dd3a246dc78c622746bd55d3cacda4c6f97ff7b05f502)
[info] > ARG_1: ECPrivateKey(2e59c250b84a4419a62273a00c6eada91f7dcdd245d16135b685946f5a87dbff,true)
[info] > Exception: java.lang.UnsatisfiedLinkError: org.bitcoin.NativeSecp256k1.secp256k1_ec_pubkey_decompress(Ljava/nio/ByteBuffer;JI)[[B
```
Seeing a lot of test failures like ☝️ which leads me to think the `secp256k1` submodule isn't... discoverable/linked?

**Comment by Christewart** [comment]
I'm not sure why travis isn't being kicked off. But yes it looks like the secp256k1 module isn't being found. Does the relative path change when incorporating a submodule? I.e. is it not `bitcoin-s-core/secp256k1` anymore?

**Comment by mecampbellsoup** [comment]
@Christewart hey, we're green again! This is a no-op change so hopefully you're OK merging 😄

**Comment by Christewart** [comment]
Merged. Congrats @mecampbellsoup . We will need to update this whenever https://github.com/bitcoin-core/secp256k1/pull/508 gets merged

**Pull request merged**
