### PR TITLE
2022 01 31 issue 4030

### LINKED ISSUE #4030: Add websocket events for Tor DLC negotiation
**Describe the bug**
We need websocket events to show the user the state of setting up Tor exchanged DLC contracts to keep them in the loop on longer running interactions. For numeric contracts especially there is longer running interaction between creating signatures and accepting and passing data back for signing. Right now there is no indication to the user that the process is ongoing.

**To Reproduce**
Steps to reproduce the behavior
1. Create a numeric offer
2. Send it to your buddy over tor
3. Wonder what state things are in until they magically click into place.

**Expected behavior**
Some indication at the UI that the tor exchange process is ongoing.

### PR DESCRIPTION
**Pull request by Christewart**
fixes #4030

This adds new states to represent when adaptor signature computation is going on. On low resource devices like the raspberry pi this can take a long time. Now with these new events emitted, UI developers can display the fact that the computation is going on and disable certain buttons while this is happening to avoid having the user corrupt their wallet.

### Alice's websocket messages
```
{"type":"dlcstatechange","payload":{"state":"Offered","dlcId":"3f0b363d0ceca8ef858a3bf16c2d26602c45ea47bc8d08f2b9d10848e6058c15","isInitiator":true,"lastUpdated":"2022-02-09T14:49:53.011Z","tempContractId":"45e807146465571e8452abf2f62ab713cb5b5195b5f9dd830072ad70e591fc07","contractInfo":"fdd82efd033a00000000000186a0fda7204e0012fda72642000400fe000186a00000fda728020000fd7530fe000186a00000fda728020000fd927cfdc3500000fda728020000fdafc8000000fda728020000fe0003ffff000000fda724020000fda712fd02dafdd824fd02d4a8f63aed240ed6e8d1547b49f8ace94ea15b8e988a692d149b55d99dca0782a2320cc53fca5b524972084beb0adb8cebd0d19833c52c40404e452482c877352e04ba9838623f02c940d20d7b185d410178cff7990c7fcf19186c7f58c7c4b8defdd822fd026e0012d95bc7089d9f8043210d37026be6ccd28f47ecd9516d8bbc1b5d22d4bdefb209c5366663636d8f6d44e469bf4be52f3e13b5381c59a2f6f929ed5d4be41485e9d61970001c874647374212f765b138de679924a4b202d5f9c7902bc4ee0f4322e3fe4f43279c5f290bd82fb5235a9e52bd845449ac0a7dcfada97acf2fd946f01d2835ee6d25a337dc6098df82c395e96c4b3290ee466e13abb3614ad6ffc98c3a00133e13a2cdf1668d900018e506e7131461102fa15a9582e7732e28c34031ef97199853de7d10f1ecd3b1118759dc4f3a765d8985e7bb5f16141af55964ef8eea7c2484bf683353e9f42d913554faf9fc9b44c1a5f66beac65d21e256497e9ad176616dd9a93cbfa0425d3bc9f0a2164d4901418b0c15d66818d16fef2ad2f73db71f67f8d2a0bba4dadc7cdc6aa0ccd91f384febe3a2450836a99bd7c29eb83b07c2c8c49fdaed50036623b568c88e28d160371a05c2e0d8a97c639a002315133dd3baa349f7ed9b31538e665ba33bd25d1f6881793eec3985e695d4a702da97da34ec7132081c7346a32edfb0e3d615c958e6ac8490aab0b3f93f922822c39896fce58d3fdb4d00330a40c1afa9f9fbb390921b147301ef6a01a525e9fac84fadfa7273754f7ff7c171e458aa5401586318f7ecc7ff1c32702c75eb96468dd27cc58e9f01c62e428fa5080daab166d5db70613b379502db832d70bc9694b0ae4c8a5bdb9317de5b42293ac2415cb715c5fa336bb73c172aeae22472c163bc22dbb9a18a9b1fd58014aa25db2bc88216e67be34985a0e4d326fca80493e761f0ff80fdd80a100002000642544355534400000000001213446572696269742d4254432d32364a414e3232","contractMaturity":0,"contractTimeout":1644364800,"feeRate":50,"totalCollateral":100000,"localCollateral":50000,"remoteCollateral":50000}}

{"type":"dlcstatechange","payload":{"state":"SignComputingAdaptorSigs","dlcId":"3f0b363d0ceca8ef858a3bf16c2d26602c45ea47bc8d08f2b9d10848e6058c15","isInitiator":true,"lastUpdated":"2022-02-09T14:52:28.651Z","tempContractId":"45e807146465571e8452abf2f62ab713cb5b5195b5f9dd830072ad70e591fc07","contractId":"8c3df95319b1907eed089cf83ade1fd7092b5a8a2726803a6b9f96669ee254c4","contractInfo":"fdd82efd033a00000000000186a0fda7204e0012fda72642000400fe000186a00000fda728020000fd7530fe000186a00000fda728020000fd927cfdc3500000fda728020000fdafc8000000fda728020000fe0003ffff000000fda724020000fda712fd02dafdd824fd02d4a8f63aed240ed6e8d1547b49f8ace94ea15b8e988a692d149b55d99dca0782a2320cc53fca5b524972084beb0adb8cebd0d19833c52c40404e452482c877352e04ba9838623f02c940d20d7b185d410178cff7990c7fcf19186c7f58c7c4b8defdd822fd026e0012d95bc7089d9f8043210d37026be6ccd28f47ecd9516d8bbc1b5d22d4bdefb209c5366663636d8f6d44e469bf4be52f3e13b5381c59a2f6f929ed5d4be41485e9d61970001c874647374212f765b138de679924a4b202d5f9c7902bc4ee0f4322e3fe4f43279c5f290bd82fb5235a9e52bd845449ac0a7dcfada97acf2fd946f01d2835ee6d25a337dc6098df82c395e96c4b3290ee466e13abb3614ad6ffc98c3a00133e13a2cdf1668d900018e506e7131461102fa15a9582e7732e28c34031ef97199853de7d10f1ecd3b1118759dc4f3a765d8985e7bb5f16141af55964ef8eea7c2484bf683353e9f42d913554faf9fc9b44c1a5f66beac65d21e256497e9ad176616dd9a93cbfa0425d3bc9f0a2164d4901418b0c15d66818d16fef2ad2f73db71f67f8d2a0bba4dadc7cdc6aa0ccd91f384febe3a2450836a99bd7c29eb83b07c2c8c49fdaed50036623b568c88e28d160371a05c2e0d8a97c639a002315133dd3baa349f7ed9b31538e665ba33bd25d1f6881793eec3985e695d4a702da97da34ec7132081c7346a32edfb0e3d615c958e6ac8490aab0b3f93f922822c39896fce58d3fdb4d00330a40c1afa9f9fbb390921b147301ef6a01a525e9fac84fadfa7273754f7ff7c171e458aa5401586318f7ecc7ff1c32702c75eb96468dd27cc58e9f01c62e428fa5080daab166d5db70613b379502db832d70bc9694b0ae4c8a5bdb9317de5b42293ac2415cb715c5fa336bb73c172aeae22472c163bc22dbb9a18a9b1fd58014aa25db2bc88216e67be34985a0e4d326fca80493e761f0ff80fdd80a100002000642544355534400000000001213446572696269742d4254432d32364a414e3232","contractMaturity":0,"contractTimeout":1644364800,"feeRate":50,"totalCollateral":100000,"localCollateral":50000,"remoteCollateral":50000,"fundingTxId":"c9d5fe477dd4c760695a370accf4a8c4c2700b1f92df5db96bed3b167b73a8c1"}}

{"type":"dlcstatechange","payload":{"state":"Signed","dlcId":"3f0b363d0ceca8ef858a3bf16c2d26602c45ea47bc8d08f2b9d10848e6058c15","isInitiator":true,"lastUpdated":"2022-02-09T14:52:34.316Z","tempContractId":"45e807146465571e8452abf2f62ab713cb5b5195b5f9dd830072ad70e591fc07","contractId":"8c3df95319b1907eed089cf83ade1fd7092b5a8a2726803a6b9f96669ee254c4","contractInfo":"fdd82efd033a00000000000186a0fda7204e0012fda72642000400fe000186a00000fda728020000fd7530fe000186a00000fda728020000fd927cfdc3500000fda728020000fdafc8000000fda728020000fe0003ffff000000fda724020000fda712fd02dafdd824fd02d4a8f63aed240ed6e8d1547b49f8ace94ea15b8e988a692d149b55d99dca0782a2320cc53fca5b524972084beb0adb8cebd0d19833c52c40404e452482c877352e04ba9838623f02c940d20d7b185d410178cff7990c7fcf19186c7f58c7c4b8defdd822fd026e0012d95bc7089d9f8043210d37026be6ccd28f47ecd9516d8bbc1b5d22d4bdefb209c5366663636d8f6d44e469bf4be52f3e13b5381c59a2f6f929ed5d4be41485e9d61970001c874647374212f765b138de679924a4b202d5f9c7902bc4ee0f4322e3fe4f43279c5f290bd82fb5235a9e52bd845449ac0a7dcfada97acf2fd946f01d2835ee6d25a337dc6098df82c395e96c4b3290ee466e13abb3614ad6ffc98c3a00133e13a2cdf1668d900018e506e7131461102fa15a9582e7732e28c34031ef97199853de7d10f1ecd3b1118759dc4f3a765d8985e7bb5f16141af55964ef8eea7c2484bf683353e9f42d913554faf9fc9b44c1a5f66beac65d21e256497e9ad176616dd9a93cbfa0425d3bc9f0a2164d4901418b0c15d66818d16fef2ad2f73db71f67f8d2a0bba4dadc7cdc6aa0ccd91f384febe3a2450836a99bd7c29eb83b07c2c8c49fdaed50036623b568c88e28d160371a05c2e0d8a97c639a002315133dd3baa349f7ed9b31538e665ba33bd25d1f6881793eec3985e695d4a702da97da34ec7132081c7346a32edfb0e3d615c958e6ac8490aab0b3f93f922822c39896fce58d3fdb4d00330a40c1afa9f9fbb390921b147301ef6a01a525e9fac84fadfa7273754f7ff7c171e458aa5401586318f7ecc7ff1c32702c75eb96468dd27cc58e9f01c62e428fa5080daab166d5db70613b379502db832d70bc9694b0ae4c8a5bdb9317de5b42293ac2415cb715c5fa336bb73c172aeae22472c163bc22dbb9a18a9b1fd58014aa25db2bc88216e67be34985a0e4d326fca80493e761f0ff80fdd80a100002000642544355534400000000001213446572696269742d4254432d32364a414e3232","contractMaturity":0,"contractTimeout":1644364800,"feeRate":50,"totalCollateral":100000,"localCollateral":50000,"remoteCollateral":50000,"fundingTxId":"c9d5fe477dd4c760695a370accf4a8c4c2700b1f92df5db96bed3b167b73a8c1"}}

{"type":"dlcstatechange","payload":{"state":"Broadcasted","dlcId":"3f0b363d0ceca8ef858a3bf16c2d26602c45ea47bc8d08f2b9d10848e6058c15","isInitiator":true,"lastUpdated":"2022-02-09T14:52:34.316Z","tempContractId":"45e807146465571e8452abf2f62ab713cb5b5195b5f9dd830072ad70e591fc07","contractId":"8c3df95319b1907eed089cf83ade1fd7092b5a8a2726803a6b9f96669ee254c4","contractInfo":"fdd82efd033a00000000000186a0fda7204e0012fda72642000400fe000186a00000fda728020000fd7530fe000186a00000fda728020000fd927cfdc3500000fda728020000fdafc8000000fda728020000fe0003ffff000000fda724020000fda712fd02dafdd824fd02d4a8f63aed240ed6e8d1547b49f8ace94ea15b8e988a692d149b55d99dca0782a2320cc53fca5b524972084beb0adb8cebd0d19833c52c40404e452482c877352e04ba9838623f02c940d20d7b185d410178cff7990c7fcf19186c7f58c7c4b8defdd822fd026e0012d95bc7089d9f8043210d37026be6ccd28f47ecd9516d8bbc1b5d22d4bdefb209c5366663636d8f6d44e469bf4be52f3e13b5381c59a2f6f929ed5d4be41485e9d61970001c874647374212f765b138de679924a4b202d5f9c7902bc4ee0f4322e3fe4f43279c5f290bd82fb5235a9e52bd845449ac0a7dcfada97acf2fd946f01d2835ee6d25a337dc6098df82c395e96c4b3290ee466e13abb3614ad6ffc98c3a00133e13a2cdf1668d900018e506e7131461102fa15a9582e7732e28c34031ef97199853de7d10f1ecd3b1118759dc4f3a765d8985e7bb5f16141af55964ef8eea7c2484bf683353e9f42d913554faf9fc9b44c1a5f66beac65d21e256497e9ad176616dd9a93cbfa0425d3bc9f0a2164d4901418b0c15d66818d16fef2ad2f73db71f67f8d2a0bba4dadc7cdc6aa0ccd91f384febe3a2450836a99bd7c29eb83b07c2c8c49fdaed50036623b568c88e28d160371a05c2e0d8a97c639a002315133dd3baa349f7ed9b31538e665ba33bd25d1f6881793eec3985e695d4a702da97da34ec7132081c7346a32edfb0e3d615c958e6ac8490aab0b3f93f922822c39896fce58d3fdb4d00330a40c1afa9f9fbb390921b147301ef6a01a525e9fac84fadfa7273754f7ff7c171e458aa5401586318f7ecc7ff1c32702c75eb96468dd27cc58e9f01c62e428fa5080daab166d5db70613b379502db832d70bc9694b0ae4c8a5bdb9317de5b42293ac2415cb715c5fa336bb73c172aeae22472c163bc22dbb9a18a9b1fd58014aa25db2bc88216e67be34985a0e4d326fca80493e761f0ff80fdd80a100002000642544355534400000000001213446572696269742d4254432d32364a414e3232","contractMaturity":0,"contractTimeout":1644364800,"feeRate":50,"totalCollateral":100000,"localCollateral":50000,"remoteCollateral":50000,"fundingTxId":"c9d5fe477dd4c760695a370accf4a8c4c2700b1f92df5db96bed3b167b73a8c1"}}
```

### Bob's websocket messages

```
{"type":"dlcstatechange","payload":{"state":"AcceptComputingAdaptorSigs","dlcId":"3f0b363d0ceca8ef858a3bf16c2d26602c45ea47bc8d08f2b9d10848e6058c15","isInitiator":false,"lastUpdated":"2022-02-09T14:51:49.828855Z","tempContractId":"45e807146465571e8452abf2f62ab713cb5b5195b5f9dd830072ad70e591fc07","contractId":"8c3df95319b1907eed089cf83ade1fd7092b5a8a2726803a6b9f96669ee254c4","contractInfo":"fdd82efd033a00000000000186a0fda7204e0012fda72642000400fe000186a00000fda728020000fd7530fe000186a00000fda728020000fd927cfdc3500000fda728020000fdafc8000000fda728020000fe0003ffff000000fda724020000fda712fd02dafdd824fd02d4a8f63aed240ed6e8d1547b49f8ace94ea15b8e988a692d149b55d99dca0782a2320cc53fca5b524972084beb0adb8cebd0d19833c52c40404e452482c877352e04ba9838623f02c940d20d7b185d410178cff7990c7fcf19186c7f58c7c4b8defdd822fd026e0012d95bc7089d9f8043210d37026be6ccd28f47ecd9516d8bbc1b5d22d4bdefb209c5366663636d8f6d44e469bf4be52f3e13b5381c59a2f6f929ed5d4be41485e9d61970001c874647374212f765b138de679924a4b202d5f9c7902bc4ee0f4322e3fe4f43279c5f290bd82fb5235a9e52bd845449ac0a7dcfada97acf2fd946f01d2835ee6d25a337dc6098df82c395e96c4b3290ee466e13abb3614ad6ffc98c3a00133e13a2cdf1668d900018e506e7131461102fa15a9582e7732e28c34031ef97199853de7d10f1ecd3b1118759dc4f3a765d8985e7bb5f16141af55964ef8eea7c2484bf683353e9f42d913554faf9fc9b44c1a5f66beac65d21e256497e9ad176616dd9a93cbfa0425d3bc9f0a2164d4901418b0c15d66818d16fef2ad2f73db71f67f8d2a0bba4dadc7cdc6aa0ccd91f384febe3a2450836a99bd7c29eb83b07c2c8c49fdaed50036623b568c88e28d160371a05c2e0d8a97c639a002315133dd3baa349f7ed9b31538e665ba33bd25d1f6881793eec3985e695d4a702da97da34ec7132081c7346a32edfb0e3d615c958e6ac8490aab0b3f93f922822c39896fce58d3fdb4d00330a40c1afa9f9fbb390921b147301ef6a01a525e9fac84fadfa7273754f7ff7c171e458aa5401586318f7ecc7ff1c32702c75eb96468dd27cc58e9f01c62e428fa5080daab166d5db70613b379502db832d70bc9694b0ae4c8a5bdb9317de5b42293ac2415cb715c5fa336bb73c172aeae22472c163bc22dbb9a18a9b1fd58014aa25db2bc88216e67be34985a0e4d326fca80493e761f0ff80fdd80a100002000642544355534400000000001213446572696269742d4254432d32364a414e3232","contractMaturity":0,"contractTimeout":1644364800,"feeRate":50,"totalCollateral":100000,"localCollateral":50000,"remoteCollateral":50000}}

{"type":"dlcstatechange","payload":{"state":"Accepted","dlcId":"3f0b363d0ceca8ef858a3bf16c2d26602c45ea47bc8d08f2b9d10848e6058c15","isInitiator":false,"lastUpdated":"2022-02-09T14:51:51.633Z","tempContractId":"45e807146465571e8452abf2f62ab713cb5b5195b5f9dd830072ad70e591fc07","contractId":"8c3df95319b1907eed089cf83ade1fd7092b5a8a2726803a6b9f96669ee254c4","contractInfo":"fdd82efd033a00000000000186a0fda7204e0012fda72642000400fe000186a00000fda728020000fd7530fe000186a00000fda728020000fd927cfdc3500000fda728020000fdafc8000000fda728020000fe0003ffff000000fda724020000fda712fd02dafdd824fd02d4a8f63aed240ed6e8d1547b49f8ace94ea15b8e988a692d149b55d99dca0782a2320cc53fca5b524972084beb0adb8cebd0d19833c52c40404e452482c877352e04ba9838623f02c940d20d7b185d410178cff7990c7fcf19186c7f58c7c4b8defdd822fd026e0012d95bc7089d9f8043210d37026be6ccd28f47ecd9516d8bbc1b5d22d4bdefb209c5366663636d8f6d44e469bf4be52f3e13b5381c59a2f6f929ed5d4be41485e9d61970001c874647374212f765b138de679924a4b202d5f9c7902bc4ee0f4322e3fe4f43279c5f290bd82fb5235a9e52bd845449ac0a7dcfada97acf2fd946f01d2835ee6d25a337dc6098df82c395e96c4b3290ee466e13abb3614ad6ffc98c3a00133e13a2cdf1668d900018e506e7131461102fa15a9582e7732e28c34031ef97199853de7d10f1ecd3b1118759dc4f3a765d8985e7bb5f16141af55964ef8eea7c2484bf683353e9f42d913554faf9fc9b44c1a5f66beac65d21e256497e9ad176616dd9a93cbfa0425d3bc9f0a2164d4901418b0c15d66818d16fef2ad2f73db71f67f8d2a0bba4dadc7cdc6aa0ccd91f384febe3a2450836a99bd7c29eb83b07c2c8c49fdaed50036623b568c88e28d160371a05c2e0d8a97c639a002315133dd3baa349f7ed9b31538e665ba33bd25d1f6881793eec3985e695d4a702da97da34ec7132081c7346a32edfb0e3d615c958e6ac8490aab0b3f93f922822c39896fce58d3fdb4d00330a40c1afa9f9fbb390921b147301ef6a01a525e9fac84fadfa7273754f7ff7c171e458aa5401586318f7ecc7ff1c32702c75eb96468dd27cc58e9f01c62e428fa5080daab166d5db70613b379502db832d70bc9694b0ae4c8a5bdb9317de5b42293ac2415cb715c5fa336bb73c172aeae22472c163bc22dbb9a18a9b1fd58014aa25db2bc88216e67be34985a0e4d326fca80493e761f0ff80fdd80a100002000642544355534400000000001213446572696269742d4254432d32364a414e3232","contractMaturity":0,"contractTimeout":1644364800,"feeRate":50,"totalCollateral":100000,"localCollateral":50000,"remoteCollateral":50000}}

{"type":"dlcstatechange","payload":{"state":"Broadcasted","dlcId":"3f0b363d0ceca8ef858a3bf16c2d26602c45ea47bc8d08f2b9d10848e6058c15","isInitiator":false,"lastUpdated":"2022-02-09T14:52:55.447Z","tempContractId":"45e807146465571e8452abf2f62ab713cb5b5195b5f9dd830072ad70e591fc07","contractId":"8c3df95319b1907eed089cf83ade1fd7092b5a8a2726803a6b9f96669ee254c4","contractInfo":"fdd82efd033a00000000000186a0fda7204e0012fda72642000400fe000186a00000fda728020000fd7530fe000186a00000fda728020000fd927cfdc3500000fda728020000fdafc8000000fda728020000fe0003ffff000000fda724020000fda712fd02dafdd824fd02d4a8f63aed240ed6e8d1547b49f8ace94ea15b8e988a692d149b55d99dca0782a2320cc53fca5b524972084beb0adb8cebd0d19833c52c40404e452482c877352e04ba9838623f02c940d20d7b185d410178cff7990c7fcf19186c7f58c7c4b8defdd822fd026e0012d95bc7089d9f8043210d37026be6ccd28f47ecd9516d8bbc1b5d22d4bdefb209c5366663636d8f6d44e469bf4be52f3e13b5381c59a2f6f929ed5d4be41485e9d61970001c874647374212f765b138de679924a4b202d5f9c7902bc4ee0f4322e3fe4f43279c5f290bd82fb5235a9e52bd845449ac0a7dcfada97acf2fd946f01d2835ee6d25a337dc6098df82c395e96c4b3290ee466e13abb3614ad6ffc98c3a00133e13a2cdf1668d900018e506e7131461102fa15a9582e7732e28c34031ef97199853de7d10f1ecd3b1118759dc4f3a765d8985e7bb5f16141af55964ef8eea7c2484bf683353e9f42d913554faf9fc9b44c1a5f66beac65d21e256497e9ad176616dd9a93cbfa0425d3bc9f0a2164d4901418b0c15d66818d16fef2ad2f73db71f67f8d2a0bba4dadc7cdc6aa0ccd91f384febe3a2450836a99bd7c29eb83b07c2c8c49fdaed50036623b568c88e28d160371a05c2e0d8a97c639a002315133dd3baa349f7ed9b31538e665ba33bd25d1f6881793eec3985e695d4a702da97da34ec7132081c7346a32edfb0e3d615c958e6ac8490aab0b3f93f922822c39896fce58d3fdb4d00330a40c1afa9f9fbb390921b147301ef6a01a525e9fac84fadfa7273754f7ff7c171e458aa5401586318f7ecc7ff1c32702c75eb96468dd27cc58e9f01c62e428fa5080daab166d5db70613b379502db832d70bc9694b0ae4c8a5bdb9317de5b42293ac2415cb715c5fa336bb73c172aeae22472c163bc22dbb9a18a9b1fd58014aa25db2bc88216e67be34985a0e4d326fca80493e761f0ff80fdd80a100002000642544355534400000000001213446572696269742d4254432d32364a414e3232","contractMaturity":0,"contractTimeout":1644364800,"feeRate":50,"totalCollateral":100000,"localCollateral":50000,"remoteCollateral":50000,"fundingTxId":"c9d5fe477dd4c760695a370accf4a8c4c2700b1f92df5db96bed3b167b73a8c1"}}

```

### CODE REVIEW

**Comment by user411** [comment]
Does it make sense to call AcceptComputingAdaptorSigs state "Accepting" and SignComputingAdaptorSigs state "Signing" at the UI?

**Comment by Christewart** [comment]
> Does it make sense to call AcceptComputingAdaptorSigs state "Accepting" and SignComputingAdaptorSigs state "Signing" at the UI?

I think so. Maybe also consider `Accept In Progress` and `Sign In Progress`. although to your point about our conversation in slack, what does "in progress" mean, is it being relayed over tor, or is it adaptor sig computation. 

You probably have a better intuition of what is better than i do.

**Comment by user411** [comment]
The "in progress" part will be a tor negotiation in progress indicator.

**Comment by Christewart** [comment]
Maybe `Building Accept` and `Building Sign` then :man_shrugging:

**Review by user411 — APPROVED** [review]

**Pull request merged**
