### PR TITLE
updates osx binaries

### PR DESCRIPTION
**Pull request by torkelrogstad**
:crossed_fingers:

### CODE REVIEW

**Comment by Christewart** [comment]
So this seems to pass CI, but i'm curious as to why the previous binaries were didn't work on your old mac. Could you paste the arch that those binaries were built on? Also can you please hash the directory, and then sign the hash with your gpg key?

**Comment by Christewart** [comment]
Can you try to build `osx_32` while we are working at this too? I think you just need to specify a compiler flag to force a 32 bit build

**Comment by torkelrogstad** [comment]
Tried building for OSX 32 bit, but running into issues: 

```
$ ./configure --enable-jni --enable-experimental --enable-module-ecdh --host=i686
...
configure: error: jni support explicitly requested but headers/dependencies were not found. Enable ECDH and try again.

$ locate jni.h
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/jni.h
/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/include/jni.h
/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/jni.h

$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk

$ echo $JNI_INCLUDE_DIRS
/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/include
```

Happy to try again if anyone with more macOS  experience than me has any input.

**Comment by torkelrogstad** [comment]
Hashing all files in directory, sorting on file name (to get consistent order), hashing again (to end up with just one hash value) and then signing: 

```
bitcoin-s/secp256k1jni/natives/osx_64 $ find -type f -exec sha256sum {} \; | sort -k 2 | sha256sum | gpg --sign --armor 
-----BEGIN PGP MESSAGE-----

owGbwMvMwMUo5yt9w/rBmrOMp72SGGL8zjAYmximmJtZJFkamqZYWlimJFkYJRum
JVmaJBlZpiWmJluaGlgmppiYphobJBqZJxsZmqelJhkCKRNzcwvL5FQFBV2uTkZj
FgZGLgZZMUWWQkZbcdVN+z49Xs8zG2YZKxPIJgYuTgGYyM4H7P80zv7bvXhJ8dLU
KbbKNlu/7Xt4Z7neLsXeMquNZ53Z/WMcON4KzGZpDu2Jrc75nSbQ42u+4u1GwVov
/zPvbx3SybQReGe/1jEoQr3i68f2T6lRWvKtFusmCJ6ojby2dfrN2caLZQsYnv19
eKZj0+clFRz5s/YxlSrU7I1Kja3ou7P298xHCSuKJ7OXVXn2bdkUuTO4ZsnM6Qw7
GVlfPXnf2B1hL3lk+bw7HHXytkz6863vdgYlL/Kf//y/VYnq8nwul7Y5K79JlqZE
HF6ocV1h064Y/d/G0zZwF1+caWJ2arGc2Zln5uETGldPOrXYjt/R6tza7okrQ+wW
VrfO+jc151v0vUO36vdFCt34WmgBAA==
=qyhX
-----END PGP MESSAGE-----
```

Should this be committed somewhere?

**Comment by torkelrogstad** [comment]
Here's a better version without the trailing dash and whitespace in the final shasum: 

```
bitcoin-s/secp256k1jni/natives/osx_64 $ find -type f -exec sha256sum {} \; | sort -k 2 | sha256sum | cut --fields 1 --delimiter=" " 
341d768b915d989db82c1fb94b29faec9509ad45e30a27c217feb121747789ce

bitcoin-s/secp256k1jni/natives/osx_64$ find -type f -exec sha256sum {} \; | sort -k 2 | sha256sum | cut --fields 1 --delimiter=" " | gpg --sign --armor
-----BEGIN PGP MESSAGE-----

owGbwMvMwMUo5yt9w/rBmrOMp92TGGL8JecbmximmJtZJFkamqZYWlimJFkYJRum
JVmaJBlZpiWmJluaGlgmppiYphobJBqZJxsZmqelJhkCKRNzcwvL5FSuTkYjFgZG
LgZZMUWWQkZbcdVN+z49Xs8zG2YTKxPIGgYuTgGYyLxO9h9zRE5/etH2tc1pkZyx
XYBLwNyvMrX7M7mL61xnP+qurQ0KZt9+djNjtcqudQzla5kYy9ykbGyXzsoPj/lW
s8W+92jIi3v8Xql3y9d0sITeEZ9a9vWs5vTFF3fqz3/7T+Cy5Sm+o077p5W83s41
d+2jbyoT97FHf5d+wHDUXkbqmdz0OSu/rPzG/YHhruyPuqT4luq8STvXqtz6llNa
yugavynw35lNQXvO9e+3Eg/5eWfN2fdx/8MT7K6apeaxMU9+034tLGzm0iM3zOOX
aiXHHHdYx1D9evlD7thDlx/EaHzmVekyipgb8F1FqaqvSpZL0UTl/ds/++ZvqCvI
PP03MHTWa8akzpx7SaeXGgMA
=GDAS
-----END PGP MESSAGE-----
```

**Pull request merged**
