### PR TITLE
Call trim on DLC message text boxes

### PR DESCRIPTION
**Pull request by benthecarman**
Was having issues when copy-pasting messages

### CODE REVIEW

**Comment by Christewart** [comment]
Is there an obvious way to manually test this?

**Comment by benthecarman** [comment]
> Is there an obvious way to manually test this?

When pasting in a contract info or announcement, add spaces to the beginning and end of what you copy

**Comment by Christewart** [comment]
> > Is there an obvious way to manually test this?
> 
> When pasting in a contract info or announcement, add spaces to the beginning and end of what you copy

@user411 Can you run through this and confirm this patch works?

**Review by user411 — APPROVED** [review]
Text box didn't seem to want to take Tabs from the keyboard, but everything went fine with extra spaces around Offer hex data. Worked fine forcing tabs into string and using that

**Pull request merged**
