### PR TITLE
Upgrade to scalac 2.12.13

### PR DESCRIPTION
**Pull request by Christewart**
https://github.com/scala/scala/releases/tag/v2.12.13

### CODE REVIEW

**Review by benthecarman — CHANGES_REQUESTED** [review]
Need to update the ci jobs to use the new version

**Review by benthecarman — APPROVED** [review]

**Comment by benthecarman** [comment]
Looks like we are getting a bunch of CI failures

**Comment by Christewart** [comment]
https://github.com/sbt/sbt/issues/6251

**Comment by Christewart** [comment]
Now the issue to follow: https://github.com/scoverage/sbt-scoverage/issues/319

**Comment by csaltos** [comment]
The error you have is at the scoverage plugin you are using with SBT ... here some info about it -> https://github.com/scoverage/sbt-scoverage/issues/295

Long story short, if you align your versions of Scala, SBT and Scoverage you can fix the runtime error.

**Comment by Christewart** [comment]
~superseded by #2729~

nvm

**Pull request merged**
