### PR TITLE
BIP 340 Update

### PR DESCRIPTION
**Pull request by nkohen**
Rebased all secp256k1 work on top of most recent BIP 340 (with even tie-breakers and new tags in hashes)

TODO: Build binaries for windows, osx

Closes #2016 
Closes #2013

### CODE REVIEW

**Review by benthecarman — APPROVED** [review]

**Comment by NicolasDorier** [comment]
~The is a bug on the sigpoint calculation.~

~if `ry` is odd, then the nonce_ge need to be negated.~

Will make a test vector for it.

**Comment by NicolasDorier** [comment]
Please add this test vector. This would have catched the bug.

```csharp
[Fact]
public void testSchnorrComputeSigPoint2()
{
	byte[] data = toByteArray("FB84860B10A497DEDDC3EFB45D20786ED72D27CFCF54A09A0E1C04DCEF4882A1");
	byte[] nonce = toByteArray("F67F8F41718C86F05EB95FAB308F5ED788A2A963124299154648F97124CAA579");
	byte[] pubKey = toByteArray("E4D36E995FF4BBA4DA2B60AD907D61D36E120D6F7314A3C2A20C6E27A5CD850F");

	byte[] pointArr = schnorrComputeSigPoint(data, nonce, pubKey, true);
	String pointStr = toHex(pointArr);
	String expectedPoint = "03C88D853DEA7F3E9C33027E99680446E4FB2ABF87704475522C8793CD1B03684B";
	assertEquals(pointStr, expectedPoint, "testSchnorrComputeSigPoint");
}
```

**Comment by NicolasDorier** [comment]
The way I fixed it, in brute forcing my way to a solution, in tryComputeSigpoint:
```csharp
if (nonce_ge.y.IsOdd)
	nonce_ge = nonce_ge.Negate();
```

**Comment by NicolasDorier** [comment]
I checked your implementation, and I missed the refactoring you did with sigpoint calculation. So this bug was only on my implementation.

**Pull request merged**
