### PR TITLE
Revamp README

### LINKED ISSUE #505: Add logo to README
https://suredbits.slack.com/archives/CB1CB4AUX/p1559919235003800

### LINKED ISSUE #507: Update README to account for 0.1 version binaries

### PR DESCRIPTION
**Pull request by torkelrogstad**
Closes #505 
Closes #507 

Users are now deferred to Bitcoin-S.org for instructions
on how to use the library. Added a logo at the top of the page as well.

The motivation for removing the majority of the README is to centralize all documentation at the website. Parts of the website is auto-generated/compiled from Scala code and sbt settings, so that's much more likely to be up to date.

### CODE REVIEW

**Comment by Christewart** [comment]
So I do think it is handy to at least keep a link for published artifacts on the README

**Comment by torkelrogstad** [comment]
Do you mean linking to Bitcoin-S.org? We could link to https://bitcoin-s.org/docs/getting-started

**Comment by Christewart** [comment]
I guess when i usually come across a github repo one of the first things i want is information how to get the binaries because I already decided to use the library, or i want to see what the latest version is. An up to date README is the convenient way for me to find that when i am looking libraries.

**Comment by torkelrogstad** [comment]
What would that look like? Seeing as we're on Maven Central, they only need to know our organization and library name

**Comment by Christewart** [comment]
Could we add a badge similar to what slick has on [their repo](https://github.com/slick/slick/) or akka on [theirs](https://github.com/akka/akka-http/)

**Comment by torkelrogstad** [comment]
Pushed a commit that removes IRC badge and adds Maven Central badge

**Pull request merged**
