### PR TITLE
Fix removing canceled DLCs from table

### PR DESCRIPTION
**Pull request by benthecarman**
Bug caused by #3321

We were not removing canceled DLCs from the table.

### CODE REVIEW

**Comment by Christewart** [comment]
Maybe @user411 can test this. Steps to test should be 

1. Pulling down a contract info from test.oracle.suredbits.com
2. Create an offer with that contract info
3. Immediately cancel it in the table view 

I believe?

**Comment by user411** [comment]
I ended up with local build errors that prevent me from running this branch. Do I have too tight of error conditions specified around the unused imports / never useds?

[error] /Users/ivan/code/bitcoin-s/async-utils/src/main/scala/org/bitcoins/asyncutil/AsyncUtil.scala:159:37: not found: value monix
[error]   private[bitcoins] val scheduler = monix.execution.Scheduler.global
[error]                                     ^
[error] /Users/ivan/code/bitcoin-s/async-utils/src/main/scala/org/bitcoins/asyncutil/AsyncUtil.scala:6:45: Unused import
[error] import java.util.concurrent.{ThreadFactory, TimeUnit}
[error]                                             ^
[error] /Users/ivan/code/bitcoin-s/async-utils/src/main/scala/org/bitcoins/asyncutil/AsyncUtil.scala:95:13: local val runnable in value $anonfun is never used
[error]         val runnable = retryRunnable(condition, p)
[error]             ^
[error] /Users/ivan/code/bitcoin-s/async-utils/src/main/scala/org/bitcoins/asyncutil/AsyncUtil.scala:149:9: local val r in method nonBlockingSleep is never used
[error]     val r: Runnable = () => p.success(())
[error]         ^
[error] four errors found

**Comment by Christewart** [comment]
> I ended up with local build errors that prevent me from running this branch. Do I have too tight of error conditions specified around the unused imports / never useds?
> 
> [error] /Users/ivan/code/bitcoin-s/async-utils/src/main/scala/org/bitcoins/asyncutil/AsyncUtil.scala:159:37: not found: value monix
> [error] private[bitcoins] val scheduler = monix.execution.Scheduler.global
> [error] ^
> [error] /Users/ivan/code/bitcoin-s/async-utils/src/main/scala/org/bitcoins/asyncutil/AsyncUtil.scala:6:45: Unused import
> [error] import java.util.concurrent.{ThreadFactory, TimeUnit}
> [error] ^
> [error] /Users/ivan/code/bitcoin-s/async-utils/src/main/scala/org/bitcoins/asyncutil/AsyncUtil.scala:95:13: local val runnable in value $anonfun is never used
> [error] val runnable = retryRunnable(condition, p)
> [error] ^
> [error] /Users/ivan/code/bitcoin-s/async-utils/src/main/scala/org/bitcoins/asyncutil/AsyncUtil.scala:149:9: local val r in method nonBlockingSleep is never used
> [error] val r: Runnable = () => p.success(())
> [error] ^
> [error] four errors found

Hmm, no i don't think so. It appears you didn't download the new dependency introduced in #3126 . Perhaps try doing a `reload` inside your sbt shell. If you are switching between branches, you need to make sure you `reload` the build configuration.

**Comment by user411** [comment]
'reload' ultimately got it

**Comment by user411** [comment]
'Cancel DLC' removed the new Offer from the list for me

**Comment by Christewart** [comment]
> 'Cancel DLC' removed the new Offer from the list for me

Ok, make sure to :heavy_check_mark: the PR then

**Review by user411 — APPROVED** [review]

**Pull request merged**
