### PR TITLE
Get both bundle and app server logging working

### LINKED ISSUE #3064: bitcoin-s bundle doesn't honor command line parameters
I've tried 

> ./bitcoin-s-bundle --datadir /tmp/bitcoin-s-demo

> ./bitcoin-s-bundle --conf /tmp/bitcoin-s-demo/bitcoin-s.conf

>./bitcoin-s-bundle --conf /tmp/bitcoin-s-demo/bitcoin-s.conf --datadir /tmp/bitcoin-s-demo

and none seem to work. it seems to keep reading `$HOME/.bitcoin-s/bitcoin-s.conf`

### LINKED ISSUE #3304: testnet3 logging broken
i am currently doing IBD, logging is working to stdout, but not being written to `$HOME/.testnet3/bitcoin-s.log`

This is on  97785561bad24a802cecfcd099706a602912a177

Screenshot from 2021-06-21 11-41-41

### PR DESCRIPTION
**Pull request by Christewart**
fixes #3304

fixes  #3064

This PR introduces a new abstraction called `ServerArgsParser` which is responsible for parsing and passing around command line args given to the server. This PR fixes the problem where bundle didn't honor the command line args, and also fixes logging problems by initializing logging sooner in the classes that extend `App` in `appServer` and `bundle`.

### CODE REVIEW

**Review by user411 — APPROVED** [review]

**Review by benthecarman — CHANGES_REQUESTED** [review]
When I try to start the bundle I get

```
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:903)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.typesafe.config.ConfigException$Missing: String: 1: No configuration setting found for key 'bitcoin-s'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:157)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:150)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:177)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:194)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:251)
	at org.bitcoins.server.BitcoinSAppConfig$.fromConfig(BitcoinSAppConfig.scala:118)
	at org.bitcoins.server.BitcoinSAppConfig$.fromDefaultDatadirWithServerArgs(BitcoinSAppConfig.scala:156)
```

**Comment by Christewart** [comment]
> When I try to start the bundle I get
> 
> ```
> Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
> 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:903)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
> 	at java.base/java.lang.Thread.run(Thread.java:832)
> Caused by: com.typesafe.config.ConfigException$Missing: String: 1: No configuration setting found for key 'bitcoin-s'
> 	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:157)
> 	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:150)
> 	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:177)
> 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
> 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:194)
> 	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:251)
> 	at org.bitcoins.server.BitcoinSAppConfig$.fromConfig(BitcoinSAppConfig.scala:118)
> 	at org.bitcoins.server.BitcoinSAppConfig$.fromDefaultDatadirWithServerArgs(BitcoinSAppConfig.scala:156)
> ```

Sigh, `--datadir` works but no `--datadir` doesn't :joy:

**Review by benthecarman — CHANGES_REQUESTED** [review]
2 problms I have found while testing:

- the `bitcoin-s-bundle.conf` is not read on startup to restore the setting you previously used

- If connecting to a testnet bitcoind, the network is not changed over

**Comment by Christewart** [comment]
> 2 problms I have found while testing:
> 
>     * the `bitcoin-s-bundle.conf` is not read on startup to restore the setting you previously used
> 
>     * If connecting to a testnet bitcoind, the network is not changed over

So i think this should be good to test again.

**Comment by benthecarman** [comment]
After hitting launch wallet I got this error

```
2021-07-07T15:06:54UTC INFO [LandingPaneModel] Writing bundle config to /home/ben/.bitcoin-s/bitcoin-s-bundle.conf
2021-07-07T15:06:55UTC ERROR [Dispatcher] String: 1-8: No configuration setting found for key 'bitcoin-s.datadir'
com.typesafe.config.ConfigException$Missing: String: 1-8: No configuration setting found for key 'bitcoin-s.datadir'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:157)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:175)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:181)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:194)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:251)
	at org.bitcoins.server.BitcoinSAppConfig$.fromConfig(BitcoinSAppConfig.scala:118)
	at org.bitcoins.bundle.gui.LandingPaneModel.$anonfun$launchWallet$6(LandingPaneModel.scala:78)
	at org.bitcoins.bundle.gui.LandingPaneModel.$anonfun$launchWallet$6$adapted(LandingPaneModel.scala:77)
```

happens with both backends

**Review by benthecarman — APPROVED** [review]
LGTM

**Comment by mahmoudeA** [comment]
> > عندما بدأوا في الوصول إلى الكوكب
> > ```
> > Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
> > 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:903)
> > 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
> > 	at java.base/java.lang.Thread.run(Thread.java:832)
> > Caused by: com.typesafe.config.ConfigException$Missing: String: 1: No configuration setting found for key 'bitcoin-s'
> > 	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:157)
> > 	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:150)
> > 	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:177)
> > 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
> > 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:194)
> > 	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:251)
> > 	at org.bitcoins.server.BitcoinSAppConfig$.fromConfig(BitcoinSAppConfig.scala:118)
> > 	at org.bitcoins.server.BitcoinSAppConfig$.fromDefaultDatadirWithServerArgs(BitcoinSAppConfig.scala:156)
> > ```
> 
> اه، إنه `--datadir`يعمل ولكن لا، `--datadir`لا يعمل 😂

**Pull request merged**
