### PR TITLE
Set closing txid on execute from View Dialog

### LINKED ISSUE #3240: Closing txid does not show up in main view
reported by a user when closing out their DLC

The closing txid does exist when examining the specific DLC

Screenshot from 2021-06-09 10-45-40

### PR DESCRIPTION
**Pull request by benthecarman**
Fixes #3240

### CODE REVIEW

**Comment by benthecarman** [comment]
Do not merge, doesn't work :/

**Comment by benthecarman** [comment]
Okay works now

**Comment by Christewart** [comment]
> Okay works now

Did you end-to-end test with someone?

**Comment by benthecarman** [comment]
> > Okay works now
> 
> Did you end-to-end test with someone?

I did a test with myself using 2 separate wallets. Took a couple iterations so didn't bring anyone else in

**Review by Christewart — APPROVED** [review]

**Pull request merged**
