### PR TITLE
Remove `BitcoinSServerMain.startedFP`

### PR DESCRIPTION
**Pull request by Christewart**
This was causing me a lot of trouble when testing #3906 and i don't really see what it was necessarily if we just return a `Future[Unit]` from `BitcoinSServerMain.run()`

### CODE REVIEW

**Comment by benthecarman** [comment]
This was originally added so the bundle could know when the server was done starting up to launch the gui

**Comment by Christewart** [comment]
> This was originally added so the bundle could know when the server was done starting up to launch the gui

Yes. I'm not sure why we didn't just return a `Future[Unit]` from `BitcoinSServerMain.run()` . This the diff on this PR

To be clear, is there something i am missing? Or does this LGTY

**Comment by benthecarman** [comment]
LGTM but haven't tested

**Comment by Christewart** [comment]
This starts up fine for me on 5c96743b5b24949ef273d57f700c3e7a97d09bee

Screenshot from 2021-12-20 13-36-59

**Review by benthecarman — APPROVED** [review]

**Pull request merged**
