### PR TITLE
Update akka deps

### PR DESCRIPTION
**Pull request by benthecarman**
Akka license did change, not sure if that is relevant here

https://www.lightbend.com/akka/license-faq

### CODE REVIEW

**Comment by Christewart** [comment]
Do you need this change immediately? I would like to see how the process plays out for pekko which is a fork of akka that may be accepted into the apache suite of libraries: 

- https://github.com/mdedetrich/akka-apache-project
- https://lists.apache.org/thread/zz8d1cshmw7w3kw09jgbt4nr722z5wj8

**Comment by benthecarman** [comment]
No this can wait

**Comment by wlk** [comment]
Hi, Any update/decision on akka->pekko migration? This is the last library we use that's not migrated

https://pekko.apache.org/docs/pekko/current/project/migration-guides.html

**Comment by Christewart** [comment]
> Hi, Any update/decision on akka->pekko migration? This is the last library we use that's not migrated
> 
> https://pekko.apache.org/docs/pekko/current/project/migration-guides.html

Working on this in #5413

**Pull request closed without merging**
