### PR TITLE
Don't allow fee unit gen to be 0

### PR DESCRIPTION
**Pull request by benthecarman**
We had a CI failure because we tried to broadcast a 0 fee transaction. Bitcoind will always reject these

https://github.com/bitcoin-s/bitcoin-s/runs/1531792984#step:5:840

### CODE REVIEW

**Review by Christewart — APPROVED** [review]

**Comment by Christewart** [comment]
So this LGTM, but one question: 

Do you think this is the root cause of the spurious CI failures we've had for broadcasting transactions? If so, we should probably reference those issues (if we have them, i can't seem to find them? I could have swore we had some though) so we can put an end to that saga for bugs.

**Comment by benthecarman** [comment]
> So this LGTM, but one question:
> 
> Do you think this is the root cause of the spurious CI failures we've had for broadcasting transactions? If so, we should probably reference those issues (if we have them, i can't seem to find them? I could have swore we had some though) so we can put an end to that saga for bugs.

Idk if this was the cause of all of them, it only had a 0.33% chance of occurring

**Comment by benthecarman** [comment]
Fixed another 0 I missed

**Comment by Christewart** [comment]
Different CI failures now:

https://github.com/bitcoin-s/bitcoin-s/runs/1538230679#step:5:1942

**Pull request merged**
