### PR TITLE
DLC connection checks and notifications

### PR DESCRIPTION
**Pull request by rorp**
Examples of Websocket payloads:

Init message:

```json
  {
    "type": "dlcconnectioninitiated",
    "payload": "localhost:12345"
  }
```

Success message:

```json
  {
    "type": "dlcconnectionestablished",
    "payload": "localhost:12345"
  }
```

Failure message:

```json
  {
    "type": "dlcconnectionfailed",
    "payload":  "localhost:12345"
  }
```

### CODE REVIEW

**Comment by Christewart** [comment]
@rorp Could you provide example payloads in the PR description?

**Comment by user411** [comment]
Does a { result: 'initiated' } response from the backend to a `checkconnection` always mean a connection was established? It does not seem to return right away all the time and I'm not sure if I'm reading the code that the future always resolves before a response or not. Sometimes I get the return value from the call before the websocket event and sometimes after.

If success/fail is available for the response, let's just send a 'success' / 'failure' or such as the result.

**Comment by user411** [comment]
If there is only one response/meaning to websocket event `dlcconnectionfailed`, let's have the payload be the address just like the `dlcconnectionestablished` event.

**Comment by user411** [comment]
I had an interesting backend interaction just now. Sent a `checkconnection` and no response came back until the serverside call timeout.

Frontend response after the call to the backend times out was
`{headers: HttpHeaders, status: 503, statusText: 'Service Unavailable' ...`

The backend did send a `dlcconnectionfailed` to match the outcome after the call 503ed it looks like from the frontend logs. This is the first time I saw a failure that happened outside of regular handling.

```
[info] 2022-09-07 20:46:00,816UTC INFO [DLCClient] connecting to SOCKS5 proxy localhost/127.0.0.1:46041
[info] 2022-09-07 20:46:00,816UTC INFO [DLCClient] connected to SOCKS5 proxy localhost/127.0.0.1:46041
[info] 2022-09-07 20:46:00,816UTC INFO [DLCClient] connecting to bz37wnhbapuxr35tfpwu2dshjh2vgz6i4utsu6jc36j5uaf7vnuz2zyd.onion:2862 via SOCKS5 localhost/127.0.0.1:46041
[info] 2022-09-07 20:46:00,820UTC ERROR [OneForOneStrategy] General failure
[info] org.bitcoins.tor.Socks5Connection$Socks5Error: General failure
[info] 	at org.bitcoins.tor.Socks5Connection$.parseConnectedAddress(Socks5Connection.scala:213)
[info] 	at org.bitcoins.tor.Socks5Connection$$anonfun$connectionRequest$1.applyOrElse(Socks5Connection.scala:65)
[info] 	at akka.actor.Actor.aroundReceive(Actor.scala:537)
[info] 	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
[info] 	at org.bitcoins.tor.Socks5Connection.aroundReceive(Socks5Connection.scala:19)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
[info] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[info] 2022-09-07 20:46:00,821UTC ERROR [DLCClient] connection failed to bz37wnhbapuxr35tfpwu2dshjh2vgz6i4utsu6jc36j5uaf7vnuz2zyd.onion:2862 via SOCKS5 localhost/127.0.0.1:46041 WARNING arguments left: 1
[info] 2022-09-07 20:46:00,821UTC ERROR [DLCClient] connection failed to bz37wnhbapuxr35tfpwu2dshjh2vgz6i4utsu6jc36j5uaf7vnuz2zyd.onion:2862 via SOCKS5 localhost/127.0.0.1:46041 WARNING arguments left: 1
[info] 2022-09-07 20:46:00,820UTC INFO [Server] Unhandled error in server:
[info] java.io.IOException: Cannot connect to bz37wnhbapuxr35tfpwu2dshjh2vgz6i4utsu6jc36j5uaf7vnuz2zyd.onion:2862 via Tor
[info] 	at org.bitcoins.dlc.node.DLCClient$$anonfun$socks5Connecting$1.$anonfun$applyOrElse$5(DLCClient.scala:91)
[info] 	at scala.Option.getOrElse(Option.scala:201)
[info] 	at org.bitcoins.dlc.node.DLCClient$$anonfun$socks5Connecting$1.applyOrElse(DLCClient.scala:90)
[info] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
[info] 	at akka.event.LoggingReceive.apply(LoggingReceive.scala:96)
[info] 	at akka.event.LoggingReceive.apply(LoggingReceive.scala:70)
[info] 	at scala.PartialFunction.applyOrElse(PartialFunction.scala:214)
[info] 	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:213)
[info] 	at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:70)
[info] 	at akka.actor.Actor.aroundReceive(Actor.scala:537)
[info] 	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
[info] 	at org.bitcoins.dlc.node.DLCClient.aroundReceive(DLCClient.scala:109)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
[info] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by user411** [comment]
Frontend to match https://github.com/bitcoin-s/bitcoin-s-ts/pull/194

**Review by user411 — APPROVED** [review]
Works in my testing

**Comment by Christewart** [comment]
This works for me too :tada:

**Pull request merged**
