### PR TITLE
2022 01 16 issue 3983

### LINKED ISSUE #3983: Failing to process blocks, taproot parsing error?
Seeing these exceptions being thrown my raspberry pi when trying to process blocks on 174c511c

The block: https://mempool.space/block/0000000000000000000a3cf29707315f6977ab47962f98cf11b54b824afe1d54

This is the tx causing the issue: https://blockstream.info/tx/37d5ec4bca7bd077992a6dd8679ab676a22986e63ebaf2c6ea1aebe5e5f5e817

```
2022-01-14T23:49:31UTC INFO [BitcoindRpcBackendUtil$] Fetching 265 blocks from bitcoind
2022-01-14T23:49:32UTC ERROR [BitcoindRpcBackendUtil$] Requesting blocks from bitcoind polling failed, range=[718447, 718712]
java.lang.IllegalArgumentException: requirement failed: Schnorr public key must be a valid x coordinate, got ByteVector(32 bytes, 0x658204033e46a1fa8cceb84013cfe2d376ca72d5f595319497b95b08aa64a970)
        at scala.Predef$.require(Predef.scala:337)
        at org.bitcoins.crypto.SchnorrPublicKey.<init>(SchnorrPublicKey.scala:12)
        at org.bitcoins.crypto.SchnorrPublicKey$.fromBytes(SchnorrPublicKey.scala:76)
        at org.bitcoins.core.protocol.script.WitnessScriptPubKeyV1.<init>(ScriptPubKey.scala:1348)
        at org.bitcoins.core.protocol.script.WitnessScriptPubKeyV1$.$anonfun$fromAsm$14(ScriptPubKey.scala:1355)
        at org.bitcoins.core.protocol.script.ScriptFactory.buildScript(ScriptFactory.scala:19)
        at org.bitcoins.core.protocol.script.ScriptFactory.buildScript$(ScriptFactory.scala:14)
        at org.bitcoins.core.protocol.script.WitnessScriptPubKeyV1$.buildScript(ScriptPubKey.scala:1351)
        at org.bitcoins.core.protocol.script.WitnessScriptPubKeyV1$.fromAsm(ScriptPubKey.scala:1356)
        at org.bitcoins.core.protocol.script.WitnessScriptPubKey$.fromAsm(ScriptPubKey.scala:1174)
        at org.bitcoins.core.protocol.script.WitnessScriptPubKey$.apply(ScriptPubKey.scala:1165)
        at org.bitcoins.core.protocol.script.ScriptPubKey$.fromAsm(ScriptPubKey.scala:1118)
        at org.bitcoins.core.serializers.script.RawScriptPubKeyParser.$anonfun$read$1(RawScriptPubKeyParser.scala:15)
        at org.bitcoins.core.util.BitcoinScriptUtil.parseScript(BitcoinScriptUtil.scala:631)
        at org.bitcoins.core.util.BitcoinScriptUtil.parseScript$(BitcoinScriptUtil.scala:620)
        at org.bitcoins.core.util.BitcoinScriptUtil$.parseScript(BitcoinScriptUtil.scala:719)
        at org.bitcoins.core.serializers.script.RawScriptPubKeyParser.read(RawScriptPubKeyParser.scala:15)
        at org.bitcoins.core.serializers.script.RawScriptPubKeyParser.read$(RawScriptPubKeyParser.scala:12)
        at org.bitcoins.core.serializers.script.RawScriptPubKeyParser$.read(RawScriptPubKeyParser.scala:23)
        at org.bitcoins.core.serializers.transaction.RawTransactionOutputParser.read(RawTransactionOutputParser.scala:34)
        at org.bitcoins.core.protocol.transaction.TransactionOutput$.fromBytes(TransactionOutput.scala:27)
        at org.bitcoins.core.protocol.transaction.TransactionOutput$.fromBytes(TransactionOutput.scala:24)
        at org.bitcoins.core.util.BytesUtil.loop$1(BytesUtil.scala:33)
        at org.bitcoins.core.util.BytesUtil.parseCmpctSizeUIntSeq(BytesUtil.scala:42)
        at org.bitcoins.core.util.BytesUtil.parseCmpctSizeUIntSeq$(BytesUtil.scala:21)
        at org.bitcoins.core.util.BytesUtil$.parseCmpctSizeUIntSeq(BytesUtil.scala:52)
        at org.bitcoins.core.protocol.transaction.BaseTransaction$.fromBytes(Transaction.scala:165)
        at org.bitcoins.core.protocol.transaction.Transaction$.fromBytes(Transaction.scala:131)
        at org.bitcoins.core.protocol.transaction.Transaction$.fromBytes(Transaction.scala:109)
        at org.bitcoins.crypto.Factory.apply(Factory.scala:53)
        at org.bitcoins.core.serializers.blockchain.RawBlockSerializer.$anonfun$read$1(RawBlockSerializer.scala:19)
        at org.bitcoins.core.serializers.RawSerializerHelper.loop$1(RawBitcoinSerializerHelper.scala:29)
        at org.bitcoins.core.serializers.RawSerializerHelper.parseCmpctSizeUIntSeq(RawBitcoinSerializerHelper.scala:39)
        at org.bitcoins.core.serializers.blockchain.RawBlockSerializer.read(RawBlockSerializer.scala:19)
        at org.bitcoins.core.protocol.blockchain.Block$.fromBytes(Block.scala:73)
        at org.bitcoins.core.protocol.blockchain.Block$.fromBytes(Block.scala:48)
        at org.bitcoins.crypto.Factory.fromHex(Factory.scala:13)
```

### PR DESCRIPTION
**Pull request by Christewart**
fixes #3983 

There is a taproot output included in the blockchain that is an invalid xonly pubkey (unless we have a bug in our crypto code!)

This PR adds another check to `WitnessScriptPubKeyV1.isValid` to be sure that the pubkey in the spk is a xonly pubkey that follows [BIP340](https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki#public-key-generation)

### CODE REVIEW

**Review by nkohen — APPROVED** [review]

**Review by benthecarman — APPROVED** [review]

**Comment by benthecarman** [comment]
Maybe should rename witness spk v1 to Taproot spk since it doesn't cover all witness v1 spks

**Comment by Christewart** [comment]
> Maybe should rename witness spk v1 to Taproot spk since it doesn't cover all witness v1 spks

I think it's a good idea. Any objections @nkohen ?

**Comment by nkohen** [comment]
> > Maybe should rename witness spk v1 to Taproot spk since it doesn't cover all witness v1 spks
> 
> I think it's a good idea. Any objections @nkohen ? 

Eh, v1 = taproot, we don't cover all of either because types restrict to good behavior, imo it sucks that invalid x-coordinates are even allowed/consensus-compatible, but I guess it saves validators a little time so that's probably why.

That said, I don't think it is necessarily a bad idea to call it Taproot regardless if we think it's nicer to work with

**Comment by Christewart** [comment]
> > > Maybe should rename witness spk v1 to Taproot spk since it doesn't cover all witness v1 spks
> > 
> > 
> > I think it's a good idea. Any objections @nkohen ?
> 
> Eh, v1 = taproot, we don't cover all of either because types restrict to good behavior, imo it sucks that invalid x-coordinates are even allowed/consensus-compatible, but I guess it saves validators a little time so that's probably why.
> 
> That said, I don't think it is necessarily a bad idea to call it Taproot regardless if we think it's nicer to work with

I'm going to merge this and file an issue about considering a rename. We can debate that later, this change itself is uncontroversial.

**Pull request merged**
