### PR TITLE
Remove SigPointComputer

### PR DESCRIPTION
**Pull request by Christewart**
After filing #3045 and seeing the performance improvements in #3046 @nkohen and I decided the abstraction isn't useful

### CODE REVIEW

**Comment by benthecarman** [comment]
Won't this harm performance

**Comment by Christewart** [comment]
> Won't this harm performance

That is what we thought, but after watching how our current code performs in visualvm it seems we have single threaded behavior (!). See #3045. 

With #3046 we restore the multi threaded behavior. I'm not sure why the current abstraction we have isn't working as expected.

**Comment by Christewart** [comment]
I encourage you to test it out yourself and confirm the behavior. The test cases I was running against are listed in #3045 . It would be good to confirm that the machine i am isn't being weird or whatever.

**Comment by Christewart** [comment]
Replaced by #3089

**Pull request closed without merging**
