### PR TITLE
Batch add filters to database

### LINKED ISSUE #1724: Database queue fills and throws an exception when syncing filters checkpoints
After running chainwork recalculation  as documetned here, I got a database error when starting to sync the node after running chain work recalc: https://github.com/bitcoin-s/bitcoin-s/pull/1697#issuecomment-666581022

The key thing from the error message below is

> Task slick.basic.BasicBackend$DatabaseDef$$anon$3@7334dd54 rejected from slick.util.AsyncExecutor$$anon$1$$anon$2@45c456b3[Running, pool size = 5, active threads = 5, queued tasks = 1000, completed tasks = 2760]

I believe slick has a default of `1000` tasks to be queue for running on the database before it throws and exception, which happens here. Why do we end up 1,000 queued tasks and we can't process them all on startup? Are we not batching upserting of compact filters?

>2020-07-30T18:14:40 DEBUG [P2P] Parsed 1 message(s) from bytes: NetworkMessage(NetworkHeader(TestNet3,cfcheckpt,UInt32Impl(57028),ByteVector(4 bytes, 0x40555c33)), CompactFilterCheckPointMessage(filterType=Basic, stopHash=DoubleSha256Digest(399b19db0deb1dfdda6c6a337a1b933be7ce2c3a5e70c02132a0267e00000000), filterHeaders=DoubleSha256Digest(22353b4ea01c7b93e55558f3e47489f6a518e8d570e0867bac3f56d013ccfd20)...DoubleSha256Digest(0bad5ec75288b82e8a441f2abcc6cd7ff41735684b073411f0971f0ca90f5095)))
2020-07-30T18:14:40 DEBUG [P2P] Unaligned bytes after this: 8132
2020-07-30T18:14:40 DEBUG [P2P] Received message=cfcheckpt from peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333) state=Normal
2020-07-30T18:14:40 DEBUG [P2P] Got 1781 checkpoints CompactFilterCheckPointMessage(filterType=Basic, stopHash=DoubleSha256Digest(399b19db0deb1dfdda6c6a337a1b933be7ce2c3a5e70c02132a0267e00000000), filterHeaders=DoubleSha256Digest(22353b4ea01c7b93e55558f3e47489f6a518e8d570e0867bac3f56d013ccfd20)...DoubleSha256Digest(0bad5ec75288b82e8a441f2abcc6cd7ff41735684b073411f0971f0ca90f5095))

### PR DESCRIPTION
**Pull request by benthecarman**
Closes #1724 

Show now batch the the adding new filters to the db.

### CODE REVIEW

**Review by Christewart — CHANGES_REQUESTED** [review]
I don't think this solves the problem. `createAll` is effectively a batching operation, it is just a batch size of 1. In #1724 it indicates there is `1000` queued tasks (batches) at the database level. You are effectively creating more tasks (batches) with this PR.

**Comment by benthecarman** [comment]
> I don't think this solves the problem. `createAll` is effectively a batching operation, it is just a batch size of 1. In #1724 it indicates there is `1000` queued tasks (batches) at the database level. You are effectively creating more tasks (batches) with this PR.

Oh, I see, misunderstood the problem.

**Comment by benthecarman** [comment]
Okay, changed it from adding each filter individually while syncing to add them in batches, like our callbacks

**Review by Christewart — APPROVED** [review]

**Review by rorp — APPROVED** [review]

**Comment by benthecarman** [comment]
Converted the variables to `Option[Int]`s

**Pull request merged**
