### PR TITLE
Pm47 secp256k1

### PR DESCRIPTION
**Pull request by Christewart**
This pull request integrates @pm47 java api enhancements in the libsecp256k1 library. The pull request is

https://github.com/bitcoin-core/secp256k1/pull/508

### CODE REVIEW

**Comment by pm47** [comment]
That's funny I was just working on integrating this in our own bitcoin-lib. Have you considered using git submodules instead of copying the secp256k1 repository?

**Comment by Christewart** [comment]
No I have not, are there particular advantages to using git submodules rather than just cloning the repo?

**Comment by pm47** [comment]
Since you have to reference the repository and a branch/commit id, I guess it is easier to keep track of exactly what version of the sources you are using. I'm trying this out, until now we were copying files...

**Comment by Christewart** [comment]
@pm47 Looks like there are some travis issues. Going to try and debug later today. 

https://travis-ci.org/bitcoin-s/bitcoin-s-core/builds/355102770#L618

**Pull request merged**
